/** Auto-generated by preBuild.mjs */
export const metaList = [
  {
    "author": "Brian Ingles",
    "slug": "animation",
    "ext": "mdx",
    "title": "Animation",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "character-animation",
    "ext": "mdx",
    "title": "Character Animation",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "css-grid",
    "ext": "mdx",
    "title": "CSS Grid",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "",
    "ext": "tsx",
    "title": "Home",
    "date": "2023-03-19"
  },
  {
    "author": "Brian Ingles",
    "slug": "ninja-animation",
    "ext": "mdx",
    "title": "Ninja Animation",
    "date": "2023-03-20"
  },
  {
    "author": "Brian Ingles",
    "slug": "threejs-animation",
    "ext": "mdx",
    "title": "Three.js Animation",
    "date": "2023-03-19"
  }
]
